//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lightbox.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lightbox.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap checkerboard {
			get {
				object obj = ResourceManager.GetObject("checkerboard", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to FreeImage couldn&apos;t be loaded and I can&apos;t load the file &apos;{0}&apos; by myself.
		///Here&apos;s a stack trace:
		///
		///{1}.
		/// </summary>
		internal static string DllNotFoundDescription {
			get {
				return ResourceManager.GetString("DllNotFoundDescription", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to FreeImage couldn&apos;t be loaded. :(.
		/// </summary>
		internal static string DllNotFoundDescriptionN {
			get {
				return ResourceManager.GetString("DllNotFoundDescriptionN", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to FreeImage DLL Not Found.
		/// </summary>
		internal static string DllNotFoundTitle {
			get {
				return ResourceManager.GetString("DllNotFoundTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to I ran into a weird error while loading the file &apos;{0}&apos;.
		///Here&apos;s a stack trace:
		///
		///{1}.
		/// </summary>
		internal static string ExceptionDescription {
			get {
				return ResourceManager.GetString("ExceptionDescription", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Weird error while loading the file &apos;{0}&apos;. :(.
		/// </summary>
		internal static string ExceptionDescriptionN {
			get {
				return ResourceManager.GetString("ExceptionDescriptionN", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Exception While Loading.
		/// </summary>
		internal static string ExceptionTitle {
			get {
				return ResourceManager.GetString("ExceptionTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Even FreeImage errored while loading the file &apos;{0}&apos;.
		///Here&apos;s a stack trace:
		///
		///{1}.
		/// </summary>
		internal static string FIExceptionDescription {
			get {
				return ResourceManager.GetString("FIExceptionDescription", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to FreeImage couldn&apos;t load the file &apos;{0}&apos;. :(.
		/// </summary>
		internal static string FIExceptionDescriptionN {
			get {
				return ResourceManager.GetString("FIExceptionDescriptionN", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to FreeImage Exception.
		/// </summary>
		internal static string FIExceptionTitle {
			get {
				return ResourceManager.GetString("FIExceptionTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The file &apos;{0}&apos; was not found. I&apos;m not sure what else to do so I&apos;ll just go down.
		///Here&apos;s a stack trace:
		///
		///{1}.
		/// </summary>
		internal static string FileNotFoundDescription {
			get {
				return ResourceManager.GetString("FileNotFoundDescription", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The file &apos;{0}&apos; was not found.  :(.
		/// </summary>
		internal static string FileNotFoundDescriptionN {
			get {
				return ResourceManager.GetString("FileNotFoundDescriptionN", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to File Not Found.
		/// </summary>
		internal static string FileNotFoundTitle {
			get {
				return ResourceManager.GetString("FileNotFoundTitle", resourceCulture);
			}
		}
	}
}
